// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfgzdvujeikkonjzqafm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmZ3pkdnVqZWlra29uanpxYWZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTgyMzYsImV4cCI6MjA2NDA3NDIzNn0.RqFaRdxdRBWLplShhjmbCI1L4IqpaLi2Upe2w3WI55U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);